### ISSUE TITLE
chai-dom link broken

### ISSUE THREAD

**Issue by jacksonrayhamilton** [chaijs/chai-docs#102]
On http://chaijs.com/plugins/chai-dom, the "View the Project on GitHub" link is broken; should be https://github.com/nathanboktae/chai-dom/, I think.

**Comment by keithamus** [comment]
Hey, thanks for the issue @jacksonrayhamilton.

This will be fixed in the upcoming site, which uses real npm data. I'll close this because there's no work to do here.
