### ISSUE TITLE
"Visit Guide" links from homepage not linking to right anchor

### ISSUE THREAD

**Issue by tiemevanveen** [chaijs/chai-docs#120]
The links from home are not linking to the right sections on http://chaijs.com/guide/styles. 
The id's seems to be right, but page is not scrolled to those id's.. maybe because of the slash? I'm not sure. 

Just letting you know. Thanks for Chai :)

**Comment by keithamus** [comment]
@tiemevanveen thanks for the issue. Could you try this again on the in-development version of the site, which is http://chaijs.github.io/chai-docs.

**Comment by tiemevanveen** [comment]
Yeah that works :)

**Comment by keithamus** [comment]
Ahh, good to know. Thanks :smile:

**Comment by tiemevanveen** [comment]
Great, no problem!
