### ISSUE TITLE
Test suite missing

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai-docs#122]
The test suite is not currently working... because, well, it doesn't exist on the new Jekyll site. 

The url is http://chaijs.com/api/test/.

**Comment by BerndErnst** [comment]
2 Months has already passed.
What is the status?
What is the scope of "currently"?

**Comment by brutalcrozt** [comment]
Thanks for reminding. I believe @keithamus have too much work to do :smile: .

**Comment by keithamus** [comment]
Yes, PRs are very much welcome 😄. Until we have a PR from the community, it is unlikely this will get fixed this year.

**Comment by keithamus** [comment]
Closes by #132
