### ISSUE TITLE
API params missing

### ISSUE THREAD

**Issue by astorije** [chaijs/chai-docs#126]
Before the website refactor, all APIs were specifying which type was expected as parameters. This was recently removed. Here is what I am talking about:

Before | After
--- | ---
<img width="724" alt="screen shot 2016-04-20 at 23 58 48" src="https://cloud.githubusercontent.com/assets/113730/14697670/01cd23ac-0754-11e6-9947-33dea52140aa.png"> | <img width="726" alt="screen shot 2016-04-20 at 23 59 03" src="https://cloud.githubusercontent.com/assets/113730/14697669/01cdeab2-0754-11e6-95c4-94721a6d77db.png">

(First screenshot courtesy of the [Internet Archive](https://web.archive.org/web/20150207063920/http://chaijs.com/api/bdd)).

I am wondering, was that on purpose or an accident? I found that really helpful (so helpful that I made sure to provide the same for [my plugin](https://github.com/astorije/chai-immutable#includevalue)). If an accident, would that be complex to re-add them?

**Comment by keithamus** [comment]
Looks like this is an accident. @astorije if you want to take a look at fixing it, that'd be awesome. Here's how the docs are currently rendered: https://github.com/chaijs/chai-docs/blob/master/_layouts/api.html#L67-L69

**Comment by keithamus** [comment]
Closed by #130
