### ISSUE TITLE
Sidebar menu scrollbar is showing in double

### ISSUE THREAD

**Issue by astorije** [chaijs/chai-docs#128]
Seen on Chrome for Mac OS X and Chrome for Android.

The sidebar menu displays 2 vertical scrollbars, one that works fine and one that stays at the top, idle.
Similarly, there is an horizontal scrollbar that gets displayed while it should not.

An animated GIF screenshot is worth a thousand GitHub issues:

![chai-docs-scrollbar](https://cloud.githubusercontent.com/assets/113730/14732792/e343b684-082b-11e6-804e-1eede29dad94.gif)

**Comment by keithamus** [comment]
Closed by #130
