### ISSUE TITLE
Documentation on 'all' needs clarification

### ISSUE THREAD

**Issue by dbooth-boston** [chaijs/chai-docs#138]
In http://chaijs.com/api/bdd/

```
.all
Sets the all flag (opposite of the any flag) later used by the keys assertion.
expect(foo).to.have.all.keys('bar', 'baz');
```

It is not clear whether 'all' means all-and-only.  I.e., it is not clear whether: (a) foo is supposed to have keys 'bar' and 'baz' (but could also have key 'bof'); or (b) foo is suppose to have *only* keys 'bar' and 'baz' (as own properties).

**Comment by meeber** [comment]
@dbooth-boston Thanks for helping with Chai. The behavior of `all` varies depending on if `have` or `contains` is present, as described [here](http://chaijs.com/api/bdd/#method_keys). Unlike `all`, most other flags are associated with multiple assertions, so details of a flag's behavior are typically located in the comments for the relevant assertion(s).

Any suggested improvements should be made [in the code comments](https://github.com/chaijs/chai/blob/e5e6f5cbbd0e3542f928559f2d290663facd82e5/lib/chai/core/assertions.js#L152-L163) in the Chai repo, as the website documentation is automatically generated from that.
