### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by AdiRishi** [chaijs/chai-docs#146]
The website http://chaijs.com/ has been down for over a day now.
![screenshot from 2017-01-12 13-01-04](https://cloud.githubusercontent.com/assets/8351234/21874137/359f6a9c-d8c7-11e6-92d2-48fac52d4067.png)

I would really appreciate it if this can be fixed quickly

**Comment by meeber** [comment]
I've been hitting the website regularly last couple days without any issues, including right after you posted this issue. Are you connecting from home, or from behind a work/school firewall?

Pinging @keithamus for more insight into the website hosting and any potential firewalls on our end.

**Comment by keithamus** [comment]
Hi @AdiRishi. thanks for the issue.

Like @meeber says, I see no problems this end, and http://www.downforeveryoneorjustme.com/chaijs.com shows it is up and not just my cache. The site his hosted on github pages so as long as you can reach github you can reach our site. You could try diagnosing any issues on your end by running `traceroute chaijs.com` (if you're on windows, that command will be `tracert chaijs.com`).

I'll close this for now, to clean up the issue tracker - but feel free to continue the conversation, we can always re-open if it is an problem we need to fix.
