### ISSUE TITLE
Chai-http website docs inconsistent with its README.md

### ISSUE THREAD

**Issue by jjjjcccjjf** [chaijs/chai-docs#155]
I don't know where to make a pull request, but http://chaijs.com/plugins/chai-http/ and https://github.com/chaijs/chai-http/blob/master/README.md are not synchronised. The latter is more updated. How can I find this?

**Comment by keithamus** [comment]
Hey @jjjjcccjjf thanks for the issue

This is automated. The README is more up to date because a release has not been made recently.
