### ISSUE TITLE
Port to gh-pages 

### ISSUE THREAD

**Issue by keithamus** [chaijs/chai-docs#74]
Given that the chai-docs website still requires manual intervention to release to http://chaijs.com, I propose we should switch the site over to Github's gh-pages. Here is a tentative to-do list of what needs to be done:

 - [x] Switch default branch over to `gh-pages`
 - [x] Look into switching site generator over to jekyll (meaning no manual release steps, just release on merge of PR)
 - [x] Make the plugins page a static page (possibly implement #34 first?)

@logicalparadox will probably have better ideas about this - feel free to edit :smile:

**Comment by logicalparadox** [comment]
Perhaps the first step of this is to generate static API documentation from the source code. Perhaps the main repo should have a `docs` folder with markdown API documentation?

This would also make it a lot easier on products such as [dash](http://kapeli.com/dash) to integrate our documentation. We should be sure to communicate with them and others of this change.

The plugins section is the major reason this has not yet occurred. #34 seems like the best way to do this, but open to other ideas if you have them. Given the importance of plugins for the Chai ecosystem and their statistical contribution to website traffic it would be ill-advised to abandon that section completely.

I will continue to release manually as long as needed, but a more hands-off approach would be preferable.

**Comment by keithamus** [comment]
I like the idea of main repo having docs, perhaps every doc could be both .md and .json - so it was parseable by a static site generator (and maybe dash & co would prefer that also?). I've raised chaijs/chai#378 to discuss further.

I've continued discussion on plugins over in #34. I'm pretty positive about where we can go with this.

I think if we look at wrapping up both #34 and chaijs/chai#378, we can then reinvestigate what it would take here to make this an automatic process.

**Comment by keithamus** [comment]
I've put up a very much WIP of a jekyll site, which ports over the existing site to jekyll pages. I'll be working on it some this weekend, but anyone who wants to chip in, please feel free!

**Comment by JaKXz** [comment]
How's this going? Any way I can contribute? :)

**Comment by keithamus** [comment]
Absolutely! Just pull down the gh-pages branch, and install jekyll (`gem install jekyll`). Run `jekyll serve` and visit the website. There's lots broken - too much to list here, but if you know enough jekyll to build a gh-pages site, you can probably work out what needs fixing and how to fix it.

You can also see the site here: https://chaijs.github.io/chai-docs/. The CSS is 404ing because we have a domain name for the main site (chaijs.com) and I havent spent the time to figure out how to get jekyll to work for both a domain and the github.io address, so the github.io address currently has no CSS. I might change it so that URLs are relative to `chai-docs` and then when its ready we can just flip the bit.

**Comment by keithamus** [comment]
I've just commented in #34 here: https://github.com/chaijs/chai-docs/issues/34#issuecomment-154366363 about getting each of the chai-plugins to include the `"chai-plugin"` keyword. So if you don't want to get your hands dirty with Jekyll, you could certainly start PRing our plugins to start using the "chai-plugin" keyword.

**Comment by keithamus** [comment]
Spent a chunk of time on this over the weekend. The [github.io page](https://chaijs.github.io/chai-docs/) is looking a lot better now. There are still big missing bits though, as a rough list:

- [ ]  individual plugin pages do not exist. Not sure how to get them working in the context of Jeykll `data` files. Maybe we need to generate a Jekyll collection for this?
- [ ] the main plugin listing isn't filterable, although it does list all tags in the sidebar.
- [ ] the guide pages are not working well, they are comprised of multiple markdown files - but they are not rendered properly in jekyll
- [ ] the actual assertion docs just don't work: https://chaijs.github.io/chai-docs/guide/styles/

**Comment by keithamus** [comment]
Closing this, in favour of making new issues which we can focus on.
