### ISSUE TITLE
Getting a 500 Error

### ISSUE THREAD

**Issue by ElijahCaine** [chaijs/chai-docs#94]
I'm not sure how else to contact y'all about this. The website returns a 500 error. Tested on two machines in different geographic regions. It's been happening for about half an hour. I'm not sure how you host it, but you should get that fixed.

**Comment by polosergio** [comment]
I am also getting a 500 server error. I can't seem to access the documentation :(

**Comment by fdaciuk** [comment]
Me too :\

**Comment by keithamus** [comment]
Sorry about the downtime all. We're working on getting it back up as soon as we can.

**Comment by fdaciuk** [comment]
@keithamus, no problem :)
Anything that we can do to help?

**Comment by keithamus** [comment]
Short term: I don't think so. The docs are run on a custom server which just needs looking at. Long term: Yes! Ideally we need to move to a more hands off platform that is easier to maintain. I've been doing some work on refactoring the site to be a jekyll one, backed by gh-pages, but I don't get a lot of time free for doing it, so checking out the gh-pages branch and fixing anything that doesn't work would be a great help! See #74 for more.

**Comment by fdaciuk** [comment]
Nice! I'll do it! :)

**Comment by logicalparadox** [comment]
Ok, we are back up, and it should function as intended.

@keithamus I would be interested to hear how your conversion is going. Let's chat soon.

Sorry all for the inconvenience.
